-- 001_schema.sql
-- Usage analytics: one append-only event log.
-- Run as the database OWNER (your own user), connected to the target database
-- (locally: ba_analytics; in production: the Neon database).

CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.events (
    event_id    uuid        PRIMARY KEY,                        -- generated by the app, blocks duplicates
    ts          timestamptz NOT NULL,                           -- when it happened (app clock, UTC)
    received_at timestamptz NOT NULL DEFAULT now(),             -- when it reached the database
    session_id  uuid        NOT NULL,                           -- random per browser session, not a person
    host        text        NOT NULL CHECK (host IN ('hf', 'render', 'local')),
    app_version text        NOT NULL,
    schema_ver  smallint    NOT NULL DEFAULT 1,
    event       text        NOT NULL CHECK (event ~ '^[a-z_]{1,40}$'),
    page        text,
    props       jsonb       NOT NULL DEFAULT '{}'::jsonb
                            CHECK (jsonb_typeof(props) = 'object')
);

-- "What did this session do, in order?"  -> sessions, funnel, timing
CREATE INDEX IF NOT EXISTS events_session_ts_idx ON analytics.events (session_id, ts);
-- "How many X per day?"                  -> counts by event type over time
CREATE INDEX IF NOT EXISTS events_event_ts_idx   ON analytics.events (event, ts);

COMMENT ON TABLE  analytics.events            IS 'Anonymous usage events from Big Ambitions Analyzer. No save data.';
COMMENT ON COLUMN analytics.events.ts         IS 'Event time on the app side (UTC).';
COMMENT ON COLUMN analytics.events.received_at IS 'Insert time on the database side. Gap vs ts = writer delay.';
COMMENT ON COLUMN analytics.events.props      IS 'Event-specific fields. See the events table in the analytics plan.';
